### ISSUE TITLE
I could not start the dev script

### ISSUE THREAD

**Issue by vikbert** [tonyrewin/svelte-boilerplate#1]
svelte-boilerplate-esbuild on  master [?] took 18s 357ms
➜ npm run dev

> svelte-boilerplate@0.0.1 dev /Users/zhoux/sites/github/svelte-projects/svelte-boilerplate-esbuild
> node esbuild.config.js

 > src/index.ts:1:16: warning: [esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead
    1 │ import App from './App.svelte'
      ╵                 ~~~~~~~~~~~~~~

 > src/App.svelte:35:17: warning: [esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead
    35 │ import Home from "./pages/Home.svelte";
       ╵                  ~~~~~~~~~~~~~~~~~~~~~

 > src/App.svelte:36:21: warning: [esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead
    36 │ import NotFound from "./pages/NotFound.svelte";
       ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~

 > src/App.svelte:37:21: warning: [esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead
    37 │ import Userlist from "./pages/Userlist.svelte";
       ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~

 > src/App.svelte:34:16: warning: [esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead
    34 │ import Nav from "./components/Nav.svelte";
       ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~

5 warnings
{
  detail: undefined,
  location: {
    column: 16,
    file: 'src/App.svelte',
    length: 25,
    line: 34,
    lineText: 'import Nav from "./components/Nav.svelte";',
    namespace: ''
  },
  notes: [],
  text: "[esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead"
}
{
  detail: undefined,
  location: {
    column: 17,
    file: 'src/App.svelte',
    length: 21,
    line: 35,
    lineText: 'import Home from "./pages/Home.svelte";',
    namespace: ''
  },
  notes: [],
  text: "[esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead"
}
{
  detail: undefined,
  location: {
    column: 21,
    file: 'src/App.svelte',
    length: 25,
    line: 36,
    lineText: 'import NotFound from "./pages/NotFound.svelte";',
    namespace: ''
  },
  notes: [],
  text: "[esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead"
}
{
  detail: undefined,
  location: {
    column: 21,
    file: 'src/App.svelte',
    length: 25,
    line: 37,
    lineText: 'import Userlist from "./pages/Userlist.svelte";',
    namespace: ''
  },
  notes: [],
  text: "[esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead"
}
{
  detail: undefined,
  location: {
    column: 16,
    file: 'src/index.ts',
    length: 14,
    line: 1,
    lineText: "import App from './App.svelte'",
    namespace: ''
  },
  notes: [],
  text: "[esbuild-svelte] The 'preprocessor' option for esbuild-svelte is deprecated, please use 'preprocess' instead"
}

**Comment by tonyrewin** [comment]
fixed https://github.com/tonyrewin/svelte-boilerplate/commit/7a35f5e9ed3509d6f6c838fc07f8a68b91171d7e
